language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - if [[ $TRAVIS_PHP_VERSION == 7.2 ]]; then
        composer require "phpunit/phpunit:^7.0" --no-update;
    else
        composer require "phpunit/phpunit:^6.1" --no-update;
    fi
  - composer update $PREFER_LOWEST

script:
  - find tests/ -name "*Test.php" | php fastest -v
  - ./fastest -x phpunit.xml.dist -v "vendor/phpunit/phpunit/phpunit {};"
  - bin/behat --config=adapters/Behat/behat.yml
